cv_build/urls.py
from django.urls import path
from . import views

app_name = 'cv_build'
urlpatterns = [
    path('info/', views.info, name="info"),
    path('<int:id>/', views.build_cv, name="build_cv"),
    path('list_of_users/', views.list_of_users, name='list_of_users')
]

my_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user_auth/', include('user_auth.urls')),
    path('cv_build/', include('cv_build.urls'))
]

user_auth/urls.py
from django.urls import path
from . import views

app_name = 'user_auth'
urlpatterns = [
    path('', views.user_login, name='login'),
    path('authenticate_user/', views.authenticate_user, name='authenticate_user'),
    path('show_user/', views.show_user, name='show_user'),
    path('reg_user/', views.reg_user, name='reg_user')
]

cv_build/models.py
from django.db import models

# Create your models here.
class Profile(models.Model):
    """This class creates objects that can be used to fill out the CV form for each user."""
    name = models.CharField(max_length=50)
    phone = models.CharField(max_length=8)
    email = models.EmailField(max_length=150)
    secondary_education = models.CharField(max_length=150)
    tertiary_education = models.CharField(max_length=150)
    degree_name = models.CharField(max_length=150)
    skill_set = models.TextField(max_length=900)
    personal_statement = models.TextField(max_length=2000)
    previous_work = models.TextField(max_length=2000)

user_auth/models.py
from django.db import models

# Create your models here.

user_auth/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class RegisterUserForm(UserCreationForm):
    first_name = forms.CharField(max_length=50)

    class Meta:
        model = User
        fields = ('username', 'first_name',  'password1', 'password2')

cv_build/views.py
from django.shortcuts import render
from .models import Profile
from django.http import HttpResponse
from django.template import loader
import pdfkit
import io

# Create your views here.
def info(request):
    if request.method=="POST":
        name=request.POST.get("name","")
        phone=request.POST.get("phone","")
        email=request.POST.get("email","")
        secondary_education=request.POST.get("secondary_education","")
        tertiary_education=request.POST.get("tertiary_education","")
        degree_name=request.POST.get("degree_name","")
        skill_set=request.POST.get("skill_set","")
        personal_statement=request.POST.get("personal_statement","")
        previous_work=request.POST.get("previous_work","")

        profile=Profile(name=name,phone=phone,email=email,secondary_education=secondary_education,tertiary_education=tertiary_education,degree_name=degree_name,skill_set=skill_set,personal_statement=personal_statement,previous_work=previous_work)
        profile.save()
    return render(request, "list_of_users.html")

def build_cv(request,id):
    profile_of_user=Profile.objects.get(pk=id)
    template = loader.get_template("build_cv.html")
    html = template.render({'profile_of_user':profile_of_user})
    option={
        'page-size':'Letter',
        'endcoding':'UTF-8'
        }
    pdf = pdfkit.from_string(html, False, option)
    response = HttpResponse(pdf,content_type='application/pdf')
    response['Contents-Disposition']="attachments"
    return response

def list_of_users(request):
    profile = Profile.objects.all()
    return render(request, "list_of_users.html",{'profile':profile})

user_auth/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.urls import reverse
from .forms import RegisterUserForm

# Create your views here.
def user_login(request):
    return render(request, 'authentication/login.html')

def authenticate_user(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)
    if user is None:
        return HttpResponseRedirect(
            reverse('user_auth:login')
        )
    else:
        login(request, user)
        return HttpResponseRedirect(
            reverse('user_auth:show_user')
        )

def show_user(request):
    """This view displays the username and encrypted password of the user after they have logged in."""
    print(request.user.username)
    return render(request, 'authentication/user.html', {
        "username":request.user.username,
        "password": request.user.password,
    })

def reg_user(request):
    """This view allows new users that are not yet on the database to register. 
    New users need to enter their username and password to register. 
    """
    if request.method == "POST":
        form = RegisterUserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            login(request,user)
            messages.success(request, ("You have successfully registered!"))
            return HttpResponseRedirect(reverse('polls:index'))
    else:
        form = RegisterUserForm()
    return render(request, 'authentication/reg_user.html', {
        'form':form,
    })

cv_build/templates/build_cv.html
<!DOCTYPE html>

<html>
    <head>
        <title>Generate CV</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    </head>

    <body>
        <h3> {{ profile_of_user.name }}</h3>
        <h4> Phone number: {{ profile_of_user.phone }}</h4>
        <h4> Email address: {{ profile_of_user.email }}</h4>
        <hr>
        <p>Personal Statement</p>
        <hr>
        <p>{{profile_of_user.personal_statement}}</p>
        <br>
        <p>Skills</p>
        <hr>
        <p>{{profile_of_user.skill_set}}</p>
        <br>
        <p>Education</p>
        <hr>
        <ul>
            <li>High school: {{ profile_of_user.secondary_education }}</li>
            <li>University: {{ profile_of_user.tertiary_education }}</li>
            <li>Degree: {{ profile_of_user.degree_name }}</li>
        </ul>
        <br>
        <p>Previous work experience</p>
        <hr>
        <p>{{ profile_of_user.previous_work }}</p>
    </body>
</html>

cv_build/templates/info.html
<!DOCTYPE html>

<html>
    <head>
        <title>Get user information</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    </head>

    <body>
        {% if user.is_authenticated %}
        <div class="container">
            <div class="row m-5">
                <div class="col-md-12">
                    <h1>Generate your CV below!</h1>
                    <hr>
                </div>
            </div>
            <div class="row m-5">
                <div class="col-md-12">
                    <h2>Enter your details below</h2>
                </div>
            </div>
            <div class="row m-5">
                <div class="col-md-7">
                    <form method="POST">
                        {% csrf_token %}
                        
                        <div class="form-group">
                            <label for="">Name</label>
                            <input type="text" class="form-control" id="name" name="name" placeholder="Enter your name">
                        </div>
                        <div class="form-group">
                            <label for="">Phone number</label>
                            <input type="text" class="form-control" id="phone" name="phone" placeholder="Enter your phone number">
                        </div>
                        <div class="form-group">
                            <label for="">Email address</label>
                            <input type="text" class="form-control" id="email" name="email" placeholder="Enter your email">
                        </div>
                        <div class="form-group">
                            <label for="">High school</label>
                            <input type="text" class="form-control" id="secondary_education" name="secondary_education" placeholder="Enter the name of the high school you attended">
                        </div>
                        <div class="form-group">
                            <label for="">University</label>
                            <input type="text" class="form-control" id="tertiary_education" name="tertiary_education" placeholder="Enter the name of the university you attended">
                        </div>
                        <div class="form-group">
                            <label for="">Degree</label>
                            <input type="text" class="form-control" id="degree_name" name="degree_name" placeholder="Enter the name of your degree">
                        </div>     
                        <div class="form-group">
                            <label for="">Skill set</label>
                            <input type="text" class="form-control" id="skill_set" name="skill_set" placeholder="Please enter a list of your skills">
                        </div>
                        <div class="form-group">
                            <label for="">About you</label>
                            <input type="text" class="form-control" id="personal_statement" name="personal_statement" placeholder="Enter a paragraph about yourself">
                        </div>
                        <div class="form-group">
                            <label for="">Previous work experience</label>
                            <input type="text" class="form-control" id="previous_work" name="previous_work" placeholder="Enter previous work experience">
                        </div>    
                        <button type="submit" class="btn btn-primary">Submit</button> 
                    </form>
                </div>
            </div>
        </div>
        {% else %}
        <h1>Sorry! You Must Be Logged In To View This Page...</h1>
        <a href="{% url 'user_auth:login' %}">Login Here</a>
        {% endif %}
    </body>
</html>

cv_build/templates/list_of_users.html
<!DOCTYPE html>

<html>
    <head>
        <title>User list</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    </head>
    <body>
        <div class="container">
            <div class="row m-5">
                <div class="cold-md-12">
                    <h2>Database Profile List</h2> 
                </div>
            </div>
            {% for profile in profile %}
            <div class="row">
                <div class="col-md-6">
                    {{profile.name}}
                </div>
                <div class="col-md-6">
                    <a href="{% url 'cv_build:build_cv' profile.id %}" class="btn btn-warning">Download CV</a>
                </div>
            </div>
            <hr>
            {% endfor %}
        </div>
    </body>
</html>

user_auth/templates/authentication/login.html
<h1> Login as User</h1>

<form action="{% url 'user_auth:authenticate_user' %}" method="post">
    {% csrf_token %}

    <label>Username</label>
    <input type="text" name="username" placeholder="User" required>
    <br/><br/>

    <label>Password</label>
    <input type="password" name="password" required>
    <br/><br/>

    <input type="submit" value="Login" />
    <br/><br/>
    <p>Not a user yet? <a href="{% url 'user_auth:reg_user' %}">Register here</a></p>
</form>

user_auth/templates/authentication/reg_user.html
{% if form.errors %}

<p>There was an error with your form.</p>

{% endif %}

<h1> Register as User</h1>

<form action="{% url 'user_auth:reg_user' %}" method="post">
    {% csrf_token %}

    {{ form.as_p }}
    <br/><br/>
    <input type="submit" value="Submit" class="btn btn-secondary"/>
</form>

user_auth/templates/authentication/user.html
<h1> Welcome, {{username}}</h1>

<p> Your password is {{password}}</p>